# Generated by Django 4.2.7 on 2024-03-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('abreviatura', models.CharField(max_length=5)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('estado', models.BooleanField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('apellido', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('galones', models.DecimalField(decimal_places=3, max_digits=10)),
                ('documento', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kilometraje', models.DecimalField(decimal_places=1, max_digits=10)),
                ('traspaso_id', models.IntegerField(blank=True, null=True)),
                ('cantidad_traspaso', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('Monto_Transpaso', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente de Pago'), ('C', 'Cancelado'), ('CP', 'Cancelado Parcialmente')], max_length=2)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_rendimiento', models.BooleanField(blank=True, default=False, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Grifo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tanqueo', models.DateTimeField()),
                ('año', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('km_recorrido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rend_kmxglp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gl_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ren_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exceso_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('carga', models.CharField(max_length=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('id_datageneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.datageneral', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='traspasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_traspaso', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('id_datageneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.datageneral', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='datageneral',
            name='grifo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.grifo'),
        ),
        migrations.AddField(
            model_name='datageneral',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.camion'),
        ),
        migrations.AddField(
            model_name='datageneral',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.producto'),
        ),
        migrations.AddField(
            model_name='camion',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.conductor'),
        ),
    ]
