# Generated by Django 4.2.7 on 2024-03-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0002_banco_camion_conductor_datageneral_grifo_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimiento',
            name='id_datageneral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.datageneral'),
        ),
    ]
