# Generated by Django 4.2.7 on 2024-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0003_alter_rendimiento_id_datageneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='datageneral',
            name='estado_omitir',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
