# Generated by Django 4.2.7 on 2023-11-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0003_group_delete_groupextension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
