# Generated by Django 4.2.7 on 2024-01-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaquinaInyeccion',
            new_name='Grifo',
        ),
    ]
