# Generated by Django 4.2.7 on 2024-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0006_rename_maquinainyeccion_grifo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grifo',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
