# Generated by Django 4.2.7 on 2024-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0008_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('apellido', models.CharField(max_length=150, unique=True)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
