# Generated by Django 4.2.7 on 2024-01-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0009_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('estado', models.BooleanField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.conductor')),
            ],
        ),
    ]
