# Generated by Django 4.2.7 on 2024-01-24 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0010_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='camion',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.conductor'),
        ),
    ]
