# Generated by Django 4.2.7 on 2024-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0013_datageneral_traspaso_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='datageneral',
            name='Monto_Transpaso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datageneral',
            name='cantidad_traspaso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
