# Generated by Django 4.2.7 on 2024-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0014_datageneral_monto_transpaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grifo',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
