# Generated by Django 4.2.7 on 2024-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0015_grifo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='grifo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
