# Generated by Django 4.2.7 on 2024-02-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0017_banco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banco',
        ),
    ]
