# Generated by Django 4.2.7 on 2024-02-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0018_delete_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('abreviatura', models.CharField(max_length=5)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
