# Generated by Django 4.2.7 on 2024-02-04 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0019_banco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataGeneral',
        ),
    ]
