# Generated by Django 4.2.7 on 2024-02-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0020_delete_datageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('galones', models.DecimalField(decimal_places=3, max_digits=10)),
                ('documento', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kilometraje', models.DecimalField(decimal_places=1, max_digits=10)),
                ('traspaso_id', models.IntegerField(blank=True, null=True)),
                ('cantidad_traspaso', models.IntegerField(blank=True, null=True)),
                ('Monto_Transpaso', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente de Pago'), ('C', 'Cancelado'), ('CP', 'Cancelado Parcialmente')], max_length=2)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.conductor')),
                ('grifo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.grifo')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.camion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.producto')),
            ],
        ),
    ]
