# Generated by Django 4.2.7 on 2024-02-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaWeb', '0021_datageneral'),
    ]

    operations = [
        migrations.AddField(
            model_name='datageneral',
            name='estado_rendimiento',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Rendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tanqueo', models.DateTimeField()),
                ('año', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('ruta', models.CharField(max_length=255)),
                ('carga', models.CharField(max_length=255)),
                ('peso', models.CharField(max_length=255)),
                ('km_recorrido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rend_kmxglp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gl_esperado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ren_esperado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exceso_real', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_datageneral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaWeb.datageneral')),
            ],
        ),
    ]
